### ISSUE TITLE
Start your first open source contribution in this repo

### ISSUE THREAD

**Issue by AnuragAnalog** [AnuragAnalog/Random-Test-Case-Generator#2]
You can start contributing to open-sourcing by making pull requests in this repo

Replicate the same program in other languages like C, Java etc.,

**Comment by NidhiNivedita6** [comment]
Can I add my Newton Raphson Method code in C?

**Comment by Mayankjha997** [comment]
hello sir!
I would like to do add rock,paper and scissor code in c language

**Comment by Amulya-coder** [comment]
@AnuragAnalog Can I add Sorting Algorithms in C to test random testcases.

**Comment by AnuragAnalog** [comment]
@NidhiNivedita6 You can add that in my other repo Numerical Analysis link: https://github.com/AnuragAnalog/Numerical-Analysis

**Comment by AnuragAnalog** [comment]
@Mayankjha997 You can add that in my other repo games link: https://github.com/AnuragAnalog/games

**Comment by AnuragAnalog** [comment]
@Amulya-coder You update the readme stating where can we use this function.

**Comment by Mayankjha997** [comment]
@AnuragAnalog  can I directly fork and start contributing : https://github.com/AnuragAnalog/games to this or first I have to take permission

**Comment by AnuragAnalog** [comment]
@Mayankjha997 You can fork and start contributing!

**Comment by Mayankjha997** [comment]
@AnuragAnalog Ok

**Comment by Amulya-coder** [comment]
@AnuragAnalog Sure.Thanks

**Comment by predator4hack** [comment]
Can I use STL in C++ for random test generator?

**Comment by Mayankjha997** [comment]
@AnuragAnalog please merge my PR #3

**Comment by AnuragAnalog** [comment]
@predator4hack you can use STL!

**Comment by AnuragAnalog** [comment]
Done with hacktoberfest 2020, thanks for your contibution guys.
